name: box-bot-ros2
version: '0.1'
summary: Differential drive Robot for ROS2
description: |
  This is an example ofa robot for ROS2 that uses differential drive.
  It was created by TheConstruct to have a bareminimum example of a robot
  simulation fro ROS2.

base: core20
confinement: devmode

parts:
  ros-demos:
    plugin: colcon
    source: https://bitbucket.org/theconstructcore/box_bot.git
    source-branch: foxy
    colcon-rosdistro: foxy
    colcon-source-space: demo_nodes_cpp
    build-packages: [make, gcc, g++]
    stage-packages: [ros-foxy-gazebo-ros-pkgs, ros-foxy-ros2launch, ros-foxy-urdf]

apps:
  box-bot-ros2-sim:
    command: opt/ros/dashing/bin/ros2 launch box_bot_gazebo box_bot_launch.py