<?xml version="1.0" ?>
<robot name="box_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find box_bot_description)/robot/materials.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/properties.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/macros.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/wheels.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/caster_wheels.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/box_bot.gazebo" />
  <xacro:include filename="$(find box_bot_description)/robot/box_bot_body.xacro" />

  <!--
  <xacro:include filename="$(find box_bot_description)/robot/box_bot_propeller.xacro" />
  -->
  
  <xacro:box_bot_body parent_name="chassis"/>

  <!--
  <xacro:link_wheel name="link_right_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:joint_wheel name="joint_right_wheel" child="link_right_wheel" origin_xyz="0 ${base_box_x / 4.0} 0" />

  <xacro:link_wheel name="link_left_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:joint_wheel name="joint_left_wheel" child="link_left_wheel" origin_xyz="0 ${-1.0 * base_box_x / 2.0} 0" />

  <xacro:caster_wheel parent="chassis" caster_wheel_name="front" origin_xyz="${base_box_x / 2.0} 0 0" />
  <xacro:caster_wheel parent="chassis" caster_wheel_name="front" origin_xyz="${-1.0 *base_box_x / 2.0} 0 0" />
  -->

</robot>
